#!groovy
// Run docker build
pipeline {
    agent {
        label 'built-in'
        }
   triggers { pollSCM('H/3 * * * *') }
    options {
        buildDiscarder(logRotator(numToKeepStr: '10', artifactNumToKeepStr: '10'))
        timestamps()
    }
    environment {
    BUILD_TAG_NAME = 'build-$BUILD_NUMBER'
    IMAGE_BASE = "danilabar/wonder_app"
    DOCKER_REPO_NAME = 'danilabar'
    IMAGE_NAME = "wonder_app"
    CHART_NAME = 'wonder-app-chart'
//    LATEST_BUILD_TAG_NAME = 'latest'
    }
    stages {
//         stage("Preparations") {
// 			steps {
// 				deleteDir() /* clean up our workspace */
// 			}
// 		}
//         stage("Checkout") {
// 			steps {
// 				checkout scm
// 			}
// 		}
        stage("Docker Login") {
            steps {
                withCredentials([usernamePassword(credentialsId: 'docker_cred', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                    sh """
                    docker login -u $USERNAME --password $PASSWORD
                    """
                }
            }
        }
        stage("Create Docker Image") {
            steps {
                dir ('.') {
                	sh """
                    docker build -t $IMAGE_BASE:$BUILD_TAG_NAME .
                    """
                }
            }
        }
        stage("Create Docker Image with Tag") {
            when { buildingTag() }
            steps {
                dir ('.') {
                	sh """
                    docker build -t $IMAGE_BASE:$TAG_NAME .
                    """
                }
            }
        }
        stage("Docker Push") {
            steps {
                sh """
                docker push -t $IMAGE_BASE:$BUILD_TAG_NAME
                """
            }
        }
        stage("Create Push with Tag") {
            when { buildingTag() }
            steps {
                dir ('.') {
                	sh """
                    docker push -t $IMAGE_BASE:$TAG_NAME
                    """
                }
            }
        }
//        stage("docker clear images") {
//            steps {
//                sh 'docker rmi -f $(docker images -a -q)'
//            }
//        }
        stage("Deploy App") {
            when { buildingTag() }
            steps {
                sh """
                helm upgrade app-prod wonder-app-chart --set image_frontend.tag=$LATEST_BUILD_TAG_NAME --install
                """
            }
        }
    }
    post {
        // Clean after build
        always {
            cleanWs(cleanWhenNotBuilt: false,
                    deleteDirs: true,
                    disableDeferredWipeout: true,
                    notFailBuild: true,
                    patterns: [[pattern: '.gitignore', type: 'INCLUDE'],
                               [pattern: '.propsfile', type: 'EXCLUDE']])
        }
    }
}